macro(find_subdirs result curdir)
  file(GLOB children RELATIVE ${curdir} ${curdir}/*)
  set(dirlist "")
  foreach(child ${children})
    if(IS_DIRECTORY ${curdir}/${child})
      list(APPEND dirlist ${child})
    endif()
  endforeach()
  SET(${result} ${dirlist})
endmacro()

set(file_prefix "${CMAKE_CURRENT_SOURCE_DIR}/src/participants")
find_subdirs(subdirs ${file_prefix})

foreach(dir ${subdirs})
	file(GLOB file_list "${file_prefix}/${dir}/*")
	foreach(file ${file_list})
		list(APPEND participant_files "${file}")
		source_group("Source\\Participants\\${dir}" FILES "${file}")
	endforeach()
endforeach()